package latte.Absyn; // Java Package generated by the BNF Converter.

public class Argument  extends Arg {
  public final Type type_;
    public final IdentP identp_;
    public int line_num, col_num, offset;

    public Argument(Type p1, IdentP p2) {
        type_ = p1;
        identp_ = p2;
    }

  public <R,A> R accept(latte.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.Argument) {
      latte.Absyn.Argument x = (latte.Absyn.Argument)o;
        return this.type_.equals(x.type_) && this.identp_.equals(x.identp_);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (this.type_.hashCode()) + this.identp_.hashCode();
  }


}
