package latte.Absyn; // Java Package generated by the BNF Converter.

public class AssArr  extends Stmt {
  public final IdentP identp_;
    public final Expr expr_1, expr_2;
  public int line_num, col_num, offset;

    public AssArr(IdentP p1, Expr p2, Expr p3) {
        identp_ = p1;
        expr_1 = p2;
        expr_2 = p3;
    }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.AssArr) {
      latte.Absyn.AssArr x = (latte.Absyn.AssArr)o;
        return this.identp_.equals(x.identp_) && this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (37 * (this.identp_.hashCode()) + this.expr_1.hashCode()) + this.expr_2.hashCode();
  }


}
