package latte.Absyn; // Java Package generated by the BNF Converter.

import compiler.LLVMAST.IntValue;
import compiler.LLVMAST.Register;
import compiler.LLVMAST.SimpleInstruction;

public class Bool extends PrimitiveType {
    public int line_num, col_num, offset;

    public Bool() {
    }

    public <R, A> R accept(latte.Absyn.PrimitiveType.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    @Override
    public String toLLVM() {
        return "i1";
    }

    @Override
    public SimpleInstruction getDefaultLLVMValue(Register register) {
        return new SimpleInstruction(register, "add", new IntValue(0), new IntValue(0), "i1");
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        return o instanceof Bool;
    }

    public int hashCode() {
        return 37;
    }

    @Override
    public String toString() {
        return "Bool";
    }
}
