package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDef  extends TopDef {
  public final String ident_;
  public final ClsBlock clsblock_;
  public int line_num, col_num, offset;
  public ClassDef(String p1, ClsBlock p2) { ident_ = p1; clsblock_ = p2; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassDef) {
      latte.Absyn.ClassDef x = (latte.Absyn.ClassDef)o;
      return this.ident_.equals(x.ident_) && this.clsblock_.equals(x.clsblock_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.clsblock_.hashCode();
  }


}
