package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDefAttr  extends ClsDef {
  public final ClsAttr clsattr_;
  public int line_num, col_num, offset;
  public ClassDefAttr(ClsAttr p1) { clsattr_ = p1; }

  public <R,A> R accept(latte.Absyn.ClsDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassDefAttr) {
      latte.Absyn.ClassDefAttr x = (latte.Absyn.ClassDefAttr)o;
      return this.clsattr_.equals(x.clsattr_);
    }
    return false;
  }

  public int hashCode() {
    return this.clsattr_.hashCode();
  }


}
