package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClassType implements java.io.Serializable {
  public abstract <R,A> R accept(ClassType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.ClassT p, A arg);

  }

}
