package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassBlock  extends ClsBlock {
  public final ListClsDef listclsdef_;
  public int line_num, col_num, offset;
  public ClassBlock(ListClsDef p1) { listclsdef_ = p1; }

  public <R,A> R accept(latte.Absyn.ClsBlock.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassBlock) {
      latte.Absyn.ClassBlock x = (latte.Absyn.ClassBlock)o;
      return this.listclsdef_.equals(x.listclsdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listclsdef_.hashCode();
  }


}
