package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDefExtend  extends TopDef {
  public final String ident_1, ident_2;
  public final ClsBlock clsblock_;
  public int line_num, col_num, offset;
  public ClassDefExtend(String p1, String p2, ClsBlock p3) { ident_1 = p1; ident_2 = p2; clsblock_ = p3; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassDefExtend) {
      latte.Absyn.ClassDefExtend x = (latte.Absyn.ClassDefExtend)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.clsblock_.equals(x.clsblock_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.clsblock_.hashCode();
  }


}
