package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassMethod  extends ClsMethod {
  public final Funct funct_;
  public int line_num, col_num, offset;
  public ClassMethod(Funct p1) { funct_ = p1; }

  public <R,A> R accept(latte.Absyn.ClsMethod.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassMethod) {
      latte.Absyn.ClassMethod x = (latte.Absyn.ClassMethod)o;
      return this.funct_.equals(x.funct_);
    }
    return false;
  }

  public int hashCode() {
    return this.funct_.hashCode();
  }


}
