package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDefExtend extends TopDef {
    public final IdentP identp_1, identp_2;
    public final ClsBlock clsblock_;
    public int line_num, col_num, offset;

    public ClassDefExtend(IdentP p1, IdentP p2, ClsBlock p3) {
        identp_1 = p1;
        identp_2 = p2;
        clsblock_ = p3;
    }

    public <R, A> R accept(latte.Absyn.TopDef.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof latte.Absyn.ClassDefExtend) {
            latte.Absyn.ClassDefExtend x = (latte.Absyn.ClassDefExtend) o;
            return this.identp_1.equals(x.identp_1) && this.identp_2.equals(x.identp_2) && this.clsblock_.equals(x.clsblock_);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (37 * (this.identp_1.hashCode()) + this.identp_2.hashCode()) + this.clsblock_.hashCode();
  }


}
