package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDefMethod  extends ClsDef {
  public final ClsMethod clsmethod_;
  public int line_num, col_num, offset;
  public ClassDefMethod(ClsMethod p1) { clsmethod_ = p1; }

  public <R,A> R accept(latte.Absyn.ClsDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassDefMethod) {
      latte.Absyn.ClassDefMethod x = (latte.Absyn.ClassDefMethod)o;
      return this.clsmethod_.equals(x.clsmethod_);
    }
    return false;
  }

  public int hashCode() {
    return this.clsmethod_.hashCode();
  }


}
