package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClsAttr implements java.io.Serializable {
  public abstract <R,A> R accept(ClsAttr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.ClassAttribute p, A arg);

  }

}
