package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClsDef implements java.io.Serializable {
  public abstract <R,A> R accept(ClsDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.ClassDefAttr p, A arg);
    public R visit(latte.Absyn.ClassDefMethod p, A arg);

  }

}
