package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClsMethod implements java.io.Serializable {
  public abstract <R,A> R accept(ClsMethod.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.ClassMethod p, A arg);

  }

}
