package latte.Absyn; // Java Package generated by the BNF Converter.

public class EApp  extends Expr {
  public final IdentP identp_;
    public final ListExpr listexpr_;
  public int line_num, col_num, offset;

    public EApp(IdentP p1, ListExpr p2) {
        identp_ = p1;
        listexpr_ = p2;
    }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EApp) {
      latte.Absyn.EApp x = (latte.Absyn.EApp)o;
        return this.identp_.equals(x.identp_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (this.identp_.hashCode()) + this.listexpr_.hashCode();
  }


}
