package latte.Absyn; // Java Package generated by the BNF Converter.

public class EArrayElem  extends Expr {
  public final IdentP identp_;
    public final Expr expr_;
  public int line_num, col_num, offset;

    public EArrayElem(IdentP p1, Expr p2) {
        identp_ = p1;
        expr_ = p2;
    }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EArrayElem) {
      latte.Absyn.EArrayElem x = (latte.Absyn.EArrayElem)o;
        return this.identp_.equals(x.identp_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (this.identp_.hashCode()) + this.expr_.hashCode();
  }


}
