package latte.Absyn; // Java Package generated by the BNF Converter.

public class EMethod  extends Expr {
  public final Expr expr_;
    public final IdentP identp_;
    public final ListExpr listexpr_;
  public int line_num, col_num, offset;

    public EMethod(Expr p1, IdentP p2, ListExpr p3) {
        expr_ = p1;
        identp_ = p2;
        listexpr_ = p3;
    }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EMethod) {
      latte.Absyn.EMethod x = (latte.Absyn.EMethod)o;
        return this.expr_.equals(x.expr_) && this.identp_.equals(x.identp_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
      return 37 * (37 * (this.expr_.hashCode()) + this.identp_.hashCode()) + this.listexpr_.hashCode();
  }


}
