package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.EVar p, A arg);
    public R visit(latte.Absyn.ELitInt p, A arg);
    public R visit(latte.Absyn.ELitTrue p, A arg);
    public R visit(latte.Absyn.ELitFalse p, A arg);
    public R visit(latte.Absyn.EApp p, A arg);
    public R visit(latte.Absyn.EString p, A arg);
    public R visit(latte.Absyn.Neg p, A arg);
    public R visit(latte.Absyn.Not p, A arg);
    public R visit(latte.Absyn.EMul p, A arg);
    public R visit(latte.Absyn.EAdd p, A arg);
    public R visit(latte.Absyn.ERel p, A arg);
    public R visit(latte.Absyn.EAnd p, A arg);
    public R visit(latte.Absyn.EOr p, A arg);

  }

}
