package latte.Absyn; // Java Package generated by the BNF Converter.

import compiler.LLVMAST.IntValue;
import compiler.LLVMAST.Value;

public class Int extends PrimitiveType {
    public int line_num, col_num, offset;

    public Int() {
    }

    public <R, A> R accept(latte.Absyn.PrimitiveType.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    @Override
    public String toLLVM() {
        return "i32";
    }

    @Override
    public Value getDefaultLLVMValue() {
        return new IntValue(0);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        return o instanceof Int;
    }

    public int hashCode() {
        return 37;
    }

    @Override
    public String toString() {
        return "Int";
    }
}
