package latte.Absyn; // Java Package generated by the BNF Converter.

public class Str extends PrimitiveType {
    public int line_num, col_num, offset;

    public Str() {
    }

    public <R, A> R accept(latte.Absyn.PrimitiveType.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    @Override
    public String toLLVM() {
        return "i8*";
    }

    @Override
    public String getDefaultLLVMValue() {
        return "@empty_string";
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        return o instanceof Str;
    }

    public int hashCode() {
        return 37;
    }

    @Override
    public String toString() {
        return "String";
    }
}
