package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class TopDef implements java.io.Serializable {
  public abstract <R,A> R accept(TopDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.FnDef p, A arg);
    public R visit(latte.Absyn.ClassDef p, A arg);
    public R visit(latte.Absyn.ClassDefExtend p, A arg);

  }

}
