package latte.Absyn; // Java Package generated by the BNF Converter.

import compiler.LLVMAST.Register;
import compiler.LLVMAST.SimpleInstruction;

public abstract class Type implements java.io.Serializable {
    public abstract <R, A> R accept(Type.Visitor<R, A> v, A arg);

    public abstract String toLLVM();

    public abstract SimpleInstruction getDefaultLLVMValue(Register register);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.ArrayT p, A arg);

        R visit(latte.Absyn.Fun p, A arg);

        R visit(latte.Absyn.Primitive p, A arg);

        R visit(latte.Absyn.Class p, A arg);

    }

}
